name: "Docker Test Action"
description: "Docker Test Action."
author: "Shane"
branding:
  icon: "type"
  color: "green"

inputs:
  tag:
    description: "Tag to Create or Update"
    required: false
    default: "test"
  summary:
    description: "Add Summary to Job"
    required: false
    default: "true"
  token:
    description: "GitHub Token"
    required: false
    default: ${{ github.token }}

outputs:
  sha:
    description: "Tag Hash"

runs:
  using: "docker"
  image: "docker://ghcr.io/smashedr/docker-test-action:v1.0.3"
