name: "Lint"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #- name: "Debug event.json"
      #  run: |
      #    cat "${GITHUB_EVENT_PATH}"

      - name: "Setup Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install"
        id: install
        run: |
          npm install prettier
          python -m pip install -U pip
          python -m pip install -Ur requirements.txt
          python -m pip install -e .
          exit 1

      - name: "Ruff"
        if: ${{ always() && steps.install.outcome == 'success' }}
        uses: astral-sh/ruff-action@v3

      - name: "Black"
        if: ${{ always() && steps.install.outcome == 'success' }}
        uses: psf/black@stable

      - name: "Mypy"
        if: ${{ always() && steps.install.outcome == 'success' }}
        run: |
          mypy src

      - name: "Isort"
        if: ${{ always() && steps.install.outcome == 'success' }}
        uses: isort/isort-action@v1

      - name: "Prettier"
        if: ${{ always() && steps.install.outcome == 'success' }}
        run: |
          npx prettier --check .
