name: "Lint"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #- name: "Debug event.json"
      #  run: |
      #    cat "${GITHUB_EVENT_PATH}"

      - name: "Setup Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install"
        run: |
          python -m pip install -U pip
          python -m pip install -r requirements.txt

      - name: "Flake8"
        if: ${{ always() }}
        run: |
          flake8 --max-line-length 119 --extend-exclude ".github" .

      - name: "Ruff"
        if: ${{ always() }}
        uses: astral-sh/ruff-action@v3

      - name: "Black"
        if: ${{ always() }}
        uses: psf/black@stable

      - name: "Isort"
        if: ${{ always() }}
        uses: isort/isort-action@v1

      - name: "Mypy"
        if: ${{ always() }}
        run: |
          mypy src

      - name: "Bandit"
        if: ${{ always() }}
        run: |
          bandit src

      - name: "Prettier"
        if: ${{ always() }}
        run: |
          npm install prettier
          npx prettier --check .

      - name: "Hadolint"
        if: ${{ always() }}
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: src/Dockerfile

      - name: "Actionlint"
        if: ${{ always() }}
        run: |
          tag=$(curl -sI https://github.com/rhysd/actionlint/releases/latest | grep -i '^location:' | sed -E 's#.*/tag/v(.*)#\1#')
          echo "tag: ${tag//[$'\t\r\n']}"
          url="https://github.com/rhysd/actionlint/releases/latest/download/actionlint_${tag//[$'\t\r\n']}_linux_amd64.tar.gz"
          echo "url: ${url}"
          curl -sL "${url}" | tar xvz -C "${RUNNER_TEMP}" actionlint
          file "${RUNNER_TEMP}/actionlint"
          "${RUNNER_TEMP}/actionlint" --version
          "${RUNNER_TEMP}/actionlint" -color -verbose
