name: "Test"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  push:
    tags: ["!**"]
    branches: ["**"]
    paths:
      - "dist/**"
      - "src/**"
      - ".github/workflows/test.yaml"
      - "package*.json"
      - "action.yml"

env:
  TAG: "test-tag"

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #- name: "Debug event.json"
      #  run: |
      #    cat "${GITHUB_EVENT_PATH}"

      - name: "Edit YAML"
        uses: Liam-Johnston/yaml-helper@V1
        if: ${{ !github.event.act }}
        with:
          file-location: "action.yml"
          create-if-does-not-exist: false
          content: |
            runs:
              image: src/Dockerfile

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          tag: ${{ env.TAG }}

      - name: "Validate Outputs"
        id: validate
        run: |
          echo "sha: '${{ steps.test.outputs.sha }}'"
          if [ "${{ steps.test.outputs.sha }}" != "${GITHUB_SHA}" ];then
            echo "Output Verification Failed: sha"
            exit 1
          fi

      #- name: "Cleanup Tag"
      #  if: ${{ always() }}
      #  continue-on-error: true
      #  run: git push origin :refs/tags/${{ env.TAG }}

      - name: "Schedule Failure Notification"
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
