name: "Test"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Edit YAML"
        uses: Liam-Johnston/yaml-helper@V1
        if: ${{ !github.event.act }}
        with:
          file-location: "action.yml"
          create-if-does-not-exist: false
          content: |
            runs:
              image: src/Dockerfile

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          tag: "test"

      - name: "Validate Outputs"
        run: |
          echo "sha: '${{ steps.test.outputs.sha }}'"
          if [ "${{ steps.test.outputs.sha }}" != "${GITHUB_SHA}" ];then
            echo "Output Verification Failed: sha"
            exit 1
          fi

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Ruff"
        uses: astral-sh/ruff-action@v3
        with:
          src: "src"

      - name: "Black"
        uses: psf/black@stable
        with:
          src: "src"
