name: "Test"

on:
  workflow_dispatch:
  #schedule:
  #  - cron: "18 18 * * 1,3,5"
  push:
    branches: ["**"]
    paths:
      - ".github/workflows/test.yaml"
      - "dist/**"
      - "src/**"
      - "package*.json"
      - "requirements*.txt"
      - "action.yml"
      - "Dockerfile"
      - "pyproject.toml"

env:
  tag: "test-tag"
  image: "false"

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v5

      - name: "Debug CTX github"
        if: ${{ !github.event.act }}
        continue-on-error: true
        env:
          GITHUB_CTX: ${{ toJSON(github) }}
        run: echo "$GITHUB_CTX"

      - name: "Edit YAML"
        if: ${{ env.image != 'true' }}
        uses: Liam-Johnston/yaml-helper@V1
        with:
          file-location: "action.yml"
          create-if-does-not-exist: false
          content: |
            runs:
              image: Dockerfile

      #- name: "Debug"
      #  if: ${{ !cancelled() }}
      #  run: |
      #    echo "github.event.act: ${{ github.event.act }}"
      #    cat action.yml

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          tag: ${{ env.tag }}

      - name: "Validate Outputs"
        id: validate
        run: |
          echo "sha: '${{ steps.test.outputs.sha }}'"
          if [ "${{ steps.test.outputs.sha }}" != "${GITHUB_SHA}" ];then
            echo "Output Verification Failed: sha"
            exit 1
          fi

      #- name: "Cleanup Tag"
      #  if: ${{ always() }}
      #  continue-on-error: true
      #  run: git push origin :refs/tags/${{ env.tag }}

      - name: "Schedule Failure Notification"
        if: ${{ failure() && github.event_name == 'schedule' }}
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
