name: "Test"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [master]

jobs:
  test:
    name: "Test"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      #- name: "Debug event.json"
      #  run: |
      #    cat "${GITHUB_EVENT_PATH}"

      - name: "Edit YAML"
        uses: Liam-Johnston/yaml-helper@V1
        if: ${{ !github.event.act }}
        with:
          file-location: "action.yml"
          create-if-does-not-exist: false
          content: |
            runs:
              image: src/Dockerfile

      - name: "Test Local Action"
        id: test
        uses: ./
        with:
          tag: "test-tag"

      - name: "Validate Outputs"
        run: |
          echo "sha: '${{ steps.test.outputs.sha }}'"
          if [ "${{ steps.test.outputs.sha }}" != "${GITHUB_SHA}" ];then
            echo "Output Verification Failed: sha"
            exit 1
          fi

  lint:
    name: "Lint"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Setup Python 3.13"
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"
          cache: "pip"

      - name: "Install"
        id: install
        run: |
          npm install prettier
          python -m pip install -U pip
          python -m pip install -Ur requirements.txt
          python -m pip install -e .

      - name: "Ruff"
        if: ${{ steps.install.outcome == 'success' }}
        uses: astral-sh/ruff-action@v3

      - name: "Black"
        if: ${{ steps.install.outcome == 'success' }}
        uses: psf/black@stable

      - name: "Mypy"
        if: ${{ steps.install.outcome == 'success' }}
        run: |
          mypy src

      - name: "Isort"
        if: ${{ steps.install.outcome == 'success' }}
        uses: isort/isort-action@v1

      - name: "Prettier"
        if: ${{ steps.install.outcome == 'success' }}
        run: |
          npx prettier --check .
